select
    player_id || '__' || analysis_period as player_period_id,
    player_id,
    analysis_period,
    index_at_utc,
    eligible_exposure_at_utc,
    period_start_at_utc,
    period_end_at_utc,
    prior_payer_status,
    platform,
    acquisition_channel,
    is_subscriber,
    has_eligible_exposure,
    is_population_eligible,
    is_window_mature,
    session_count,
    session_duration_seconds,
    liveops_participation_count,
    subscription_net_revenue_usd,
    standalone_store_net_revenue_usd,
    reward_track_net_revenue_usd,
    total_net_revenue_usd,
    standalone_transaction_count,
    discounted_standalone_transaction_count,
    discount_amount_usd
from {{ ref('int_hybrid_subscription__player_28d_behavior') }}
