"""The rule catalogue as a Markdown document, generated from the rule code.

The committed copy is docs/rules.md. Regenerate it, from the linesman/ folder, with

    python -m linesman.rules.docs > docs/rules.md

A test fails when the committed file differs from what this module produces, so the
documentation cannot drift from the rules: edit a rule's text in the rule, then regenerate.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence

from linesman.rules import ALL_RULES, Rule

GROUPS = {
    "NAM": "Naming",
    "SCH": "Schema",
    "DOC": "Documentation",
    "GOV": "Governance",
    "COV": "Coverage",
}

_INTRO = """\
# Rule catalogue

Generated from the rule code by `python -m linesman.rules.docs`. Do not edit this file by hand:
a test fails if it differs from the generated text. To change a rule, change it in
`src/linesman/rules/` and regenerate.

A **rule** looks at one validated plan and either finds nothing or raises one **finding**. Each
finding carries the rule's ID and severity, the evidence that triggered it, why it matters,
what to do, and its references. The same plan always gives the same findings.

| Severity | Effect on the review |
| --- | --- |
| blocker | The recommendation is `revise` and `linesman review-plan` exits with status 1. |
| warning | Reported; the recommendation stays `proceed`. |
| info | Reported; the recommendation stays `proceed`. |

Linesman is advisory. A recommendation of `proceed` means the plan raised none of the
objections below, not that the tracking is correct: Linesman reads the plan, never the data
the product actually sends.
"""


def render_rules_markdown(rules: Sequence[Rule] = ALL_RULES) -> str:
    parts = [_INTRO]
    for prefix, group in GROUPS.items():
        members = [rule for rule in rules if rule.id.startswith(prefix)]
        if not members:
            continue
        parts.append(f"\n## {group}\n")
        for rule in members:
            parts.append(
                f"### {rule.id}: {rule.title}\n\n"
                f"- **Severity:** {rule.severity}\n"
                f"- **Fires when:** {rule.fires_when}\n"
                f"- **Why it matters:** {rule.why_it_matters}\n"
                f"- **What to do:** {rule.remediation}\n"
            )
            if rule.references:
                parts.append("- **References:**\n" + "".join(f"  - {r}\n" for r in rule.references))
            parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


if __name__ == "__main__":
    sys.stdout.write(render_rules_markdown())
