"""The rule catalogue as a Markdown document, generated from the rule code.

The committed copy is docs/rules.md. Regenerate it, from the referee/ folder, with

    python -m referee.rules.docs > docs/rules.md

A test fails when the committed file differs from what this module produces, so the
documentation cannot drift from the rules: edit a rule's text in the rule, then regenerate.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence

from referee.rules import CATALOGUE, Rule

GROUPS = {
    "HYP": "Hypothesis",
    "DES": "Design",
    "PRO": "Procedure",
    "RES": "Results",
}

_INTRO = """\
# Rule catalogue

Generated from the rule code by `python -m referee.rules.docs`. Do not edit this file by hand:
a test fails if it differs from the generated text. To change a rule, change it in
`src/referee/rules/` and regenerate.

A **rule** looks at one validated spec and either finds nothing or raises one **finding**. Each
finding carries the rule's ID and severity, the evidence that triggered it, why it matters,
what to do, and its references. The same spec always gives the same findings.

| Severity | Effect on the review |
| --- | --- |
| blocker | The recommendation is `revise` and `referee review-design` exits with status 1. |
| warning | Reported; the recommendation stays `proceed`. |
| info | Reported; the recommendation stays `proceed`. |

Referee is advisory. A recommendation of `proceed` means the design raised none of the
objections below, not that the experiment is worth running.

In "fires when", a field is **absent** when it is missing from the spec or is `null`.
Whether a spec is well-formed (a hypothesis with a null statement, a direction and a metric, for
example) is decided before any rule runs, and a spec that fails that check gets exit status 2
instead of a review. HYP-001 covers the one case that check cannot see.
"""

_POWER_NOTES = """\
## How the power plan behind DES-001, DES-004 and DES-005 is computed

- Sample sizes use a normal approximation built on the standard library. The tests compare them
  with statsmodels.
- For a proportion the variance under the null is pooled across the arms. For a continuous or
  ratio metric `baseline_std` is the standard deviation of one unit's value, and for a ratio
  metric it is the standard deviation of the ratio itself.
- Every variant must reach the target power against the control. The most demanding
  variant-versus-control comparison sets the total, and each arm gets its allocated share of it.
- A two-sided test splits alpha between the two tails. For a proportion with a two-sided
  hypothesis the plan covers whichever direction needs more units.
- With more than two arms, alpha is divided by the number of variant-versus-control comparisons
  (Bonferroni), unless `design.alpha_adjustment` is `none`. A spec that declares `dunnett` is
  planned with Bonferroni, which asks for slightly more units than Dunnett would.
- Required days are the total divided by `daily_eligible_units`, rounded up. The whole-week figure
  rounds that up to a multiple of 7.
- The detectable effect that DES-001 reports is the smallest relative effect the planned
  duration can power, found by bisection.
"""

_RESULTS_NOTE = """\
A results rule looks at an experiment's exported data together with its spec (design
section 21), not at the spec alone. A results review ends in a **verdict**, which follows from
the findings: `invalid` if any is a blocker, `caution` if any is a warning, `clear` otherwise.
`clear` says that the rules which ran found nothing; it does not say the effect is real. The
design review does not run these rules.
"""

_OUTRO = """\
## Not yet

The rest of the `RES` family in design section 21 arrives with the results review; no command
runs the results rules yet.
"""


def _severity_counts(rules: Sequence[Rule]) -> str:
    counts = {s: sum(rule.severity == s for rule in rules) for s in ("blocker", "warning", "info")}
    return (
        f"{len(rules)} rules: {counts['blocker']} blockers, "
        f"{counts['warning']} warnings, {counts['info']} info."
    )


def _group(rule: Rule) -> str:
    prefix = rule.id.split("-")[0]
    if prefix not in GROUPS:
        raise ValueError(f"{rule.id} has no group: add {prefix!r} to GROUPS")
    return prefix


def _rule_block(rule: Rule) -> str:
    references = (
        ["- **References:**", *(f"  - {reference}" for reference in rule.references)]
        if rule.references
        else ["- **References:** none"]
    )
    return "\n".join(
        [
            f"### {rule.id}: {rule.title}",
            "",
            f"- **Severity:** {rule.severity}",
            f"- **Fires when:** {rule.fires_when}",
            f"- **Why it matters:** {rule.why_it_matters}",
            f"- **What to do:** {rule.remediation}",
            *references,
        ]
    )


def render_rules_markdown(rules: Sequence[Rule] = CATALOGUE) -> str:
    """The catalogue for `rules`, grouped by ID prefix in the order the groups are listed."""
    table = ["| ID | Severity | Title |", "| --- | --- | --- |"]
    table += [f"| {rule.id} | {rule.severity} | {rule.title} |" for rule in rules]
    blocks = [_INTRO, "## Summary", _severity_counts(rules), "\n".join(table)]
    for prefix, name in GROUPS.items():
        members = [rule for rule in rules if _group(rule) == prefix]
        if members:
            blocks.append(f"## {name} rules ({prefix})")
            if prefix == "RES":
                blocks.append(_RESULTS_NOTE)
            blocks += [_rule_block(rule) for rule in members]
    blocks += [_POWER_NOTES, _OUTRO]
    return "\n\n".join(block.strip("\n") for block in blocks) + "\n"


def main() -> None:
    sys.stdout.write(render_rules_markdown())


if __name__ == "__main__":
    main()
