name: "game_analytics"
version: "1.0.0"
config-version: 2

profile: "game_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_data_root: "../data/raw"

models:
  game_analytics:
    shared:
      +schema: shared
      +tags: [shared]
    live_strategy:
      +schema: live_strategy
      +tags: [live_strategy]
    subscription:
      +schema: subscription
      +tags: [subscription]
    hybrid_subscription:
      +schema: hybrid_subscription
      +tags: [hybrid_subscription]
