"""The recognised column headers as a Markdown document, generated from the code.

The committed copy is docs/column-names.md. Regenerate it, from the tracewright/ folder, with

    python -m tracewright.sheets.docs > docs/column-names.md

A test fails when the committed file differs from what this module produces, so the list cannot
drift from the spellings the importer actually recognises.
"""

from __future__ import annotations

import sys

from tracewright.sheets.layout import ALIASES, CANONICAL
from tracewright.sheets.values import STATUS_WORDS, TYPE_WORDS, UNSUPPORTED_TYPE_WORDS

MEANING = {
    "event": "The event name. Required.",
    "property": "The property name. Empty on a row that describes the event only.",
    "type": "The property's data type (see the words below). Empty means `string`.",
    "required": "Whether the property is always sent (yes/no, true/false, 1/0, a tick).",
    "pii": "Whether the property is personal data (same spellings).",
    "allowed_values": (
        "For an `enum`: the permitted values (a bar, semicolon, comma or newline between)."
    ),
    "description": "Of the property on a property row; of the event on a row with no property.",
    "event_description": (
        "Of the event, on any row. If present, `description` is only the property's."
    ),
    "trigger": "When the event is sent. Describes the event; the same on every row of it.",
    "owner": "Who owns the event. Describes the event.",
    "status": "`active`, `planned` or `deprecated` (see the words below). Describes the event.",
}

_INTRO = """\
# Column names and cell words the importer recognises

Generated from the code by `python -m tracewright.sheets.docs`. Do not edit this file by hand: a
test fails if it differs from the generated text. To change what is recognised, change
`src/tracewright/sheets/layout.py` or `values.py` and regenerate.

A header is compared with case, spaces and punctuation ignored, so `Event Name`, `event_name` and
`EVENT NAME*` are all the spelling `eventname`. A header that is not in the table can be named with
`--map NAME=HEADER`. Two columns that both fit one meaning are an error until you choose with
`--map`. A column that fits no meaning is refused unless you add `--ignore-other-columns`.

## Meanings and the header spellings recognised for each

| Meaning | What it is | Recognised headers (as compared) |
| --- | --- | --- |
"""


def _words(mapping: dict[str, str], target: str) -> str:
    return ", ".join(f"`{w}`" for w, t in mapping.items() if t == target)


def render() -> str:
    lines = [_INTRO.rstrip("\n")]
    for name in CANONICAL:
        spellings = ", ".join(f"`{a}`" for a in ALIASES[name])
        lines.append(f"| `{name}` | {MEANING[name]} | {spellings} |")
    lines += [
        "",
        "## Type words",
        "",
        "Parentheses and what follows them are ignored (`string (max 50)`).",
        "",
    ]
    lines += ["| Plan type | Words |", "| --- | --- |"]
    for target in ("string", "integer", "number", "boolean", "timestamp", "enum"):
        lines.append(f"| `{target}` | {_words(TYPE_WORDS, target)} |")
    unsupported = ", ".join(f"`{w}`" for w in sorted(UNSUPPORTED_TYPE_WORDS))
    lines += [
        "",
        f"Refused with a reason, because a plan has no lists or objects: {unsupported}. "
        "Add a word of your own with `--type-map 'Word=string'`.",
        "",
        "## Status words",
        "",
        "| Plan status | Words |",
        "| --- | --- |",
    ]
    for target in ("active", "planned", "deprecated"):
        lines.append(f"| `{target}` | {_words(STATUS_WORDS, target)} |")
    lines += [
        "",
        "Add a word of your own with `--status-map 'Word=planned'`.",
        "",
        "## Yes and no",
        "",
        "For `required` and `pii`. Yes: `true`, `t`, `yes`, `y`, `1`, `x`, `required`, "
        "`mandatory`, a tick (✓ ✔ ☑). No: `false`, `f`, `no`, `n`, `0`, `optional`, "
        "`-`, a cross (✗ ✘ ☐). An empty cell is left unset.",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.stdout.write(render())
